<?php
/**
 * Transient-backed trace storage.
 *
 * @package EditTrace
 */

declare( strict_types=1 );

namespace EditTrace\Inspector;

/**
 * Stores trace registries in WordPress transients. When a persistent object
 * cache is present the data never touches the database; otherwise it lives
 * in wp_options with an expiration and is purged by WordPress' scheduled
 * transient cleanup (and by our own hourly sweep).
 */
final class TransientTraceStorage implements TraceStorage {

	public const PREFIX = 'edittrace_trace_';

	public function save( string $token, array $data, int $ttl ): bool {
		if ( ! self::is_valid_token( $token ) ) {
			return false;
		}
		return set_transient( self::PREFIX . $token, $data, max( 60, $ttl ) );
	}

	public function load( string $token ): ?array {
		if ( ! self::is_valid_token( $token ) ) {
			return null;
		}
		$data = get_transient( self::PREFIX . $token );
		return is_array( $data ) ? $data : null;
	}

	public function delete( string $token ): void {
		if ( self::is_valid_token( $token ) ) {
			delete_transient( self::PREFIX . $token );
		}
	}

	/**
	 * Tokens are 32 hex characters generated by TraceSession.
	 */
	public static function is_valid_token( string $token ): bool {
		return 1 === preg_match( '/^[a-f0-9]{32}$/', $token );
	}

	/**
	 * Removes expired trace transients from the options table (no-op with an
	 * external object cache, where expiry is handled by the cache itself).
	 */
	public static function purge_expired(): void {
		if ( wp_using_ext_object_cache() ) {
			return;
		}
		global $wpdb;
		$like = $wpdb->esc_like( '_transient_timeout_' . self::PREFIX ) . '%';
		$rows = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT option_name FROM {$wpdb->options} WHERE option_name LIKE %s AND option_value < %d LIMIT 200",
				$like,
				time()
			)
		);
		foreach ( (array) $rows as $option_name ) {
			$token = substr( (string) $option_name, strlen( '_transient_timeout_' . self::PREFIX ) );
			delete_transient( self::PREFIX . $token );
		}
	}
}
